name: robotik
channels:
  - default
  - conda-forge
dependencies:
  - python>3.6.0
  - pandas=0.25.0
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - pip>19.2.0
  - numpy=1.17.3
  #- rpi=0.6.2
  #- pip:
  #    - gpiozero=1.5.1